apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: gemini-crop-adviser
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "elb"
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80