spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      timeout: 2000ms

twilio:
  phoneNumber: ${TWILIO_PHONE_NUMBER}
  account_sid: ${TWILIO_ACCOUNT_SID}
  auth_token: ${TWILIO_AUTH_TOKEN}

jwt:
  secret: ${JWT_SECRET}
  access-token-ms: ${JWT_ACCESS_TOKEN_MS}
  refresh-token-ms: ${JWT_REFRESH_TOKEN_MS}
  cleanup:
    cron: "0 0 0 * * ?"

otp:
  expiration:
    minutes: ${OTP_EXPIRATION_MINUTES}

sms:
  mock:
    enabled: ${SMS_MOCK_ENABLED}

server:
  port: 8080

logging:
  level:
    com.yourpackage: INFO
    org.springframework.security: WARN