apiVersion: v1
kind: Service
metadata:
  name: producer-service
  namespace: gemini-crop-adviser
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "elb"
spec:
  type: LoadBalancer
  selector:
    app: producer-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081